feat: 사용자 프로필 수정 페이지 개발
team-pream/pream-web pull request #101
Opened 2024-11-03 15:42 UTC by jeonkyungwon

### PR 제목

[PREAM-143]

### 🔗 연관된 이슈 번호

close #100 

### ✨ 어떤 기능을 개발했나요?
사용자 프로필 수정 페이지 UI 개발
사용자 프로필 수정 기능 개발
### ✅ 어떤 문제를 해결했나요?
-
### 🗂️ 관련 논의 내용 Link (Option)
-
### 🚀 결과 이미지 (Option)
-

2024-11-04 00:12 UTC, corinthionia requested changes

2024-11-04 00:12 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +          errorMessage={isNicknameAvailable === false ? '이미 존재하는 닉네임입니다' : ''}
빈 문자열을 넘기는 것보다는 이렇게 하는 게 더 좋을 것 같아요
```suggestion
          confirmMessage={isNicknameAvailable && '사용 가능한 닉네임입니다'}
          errorMessage={!isNicknameAvailable && '이미 존재하는 닉네임입니다'}
```

2024-11-04 00:12 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +          errorMessage={isNicknameAvailable === false ? '이미 존재하는 닉네임입니다' : ''}
그리고 닉네임 형식에 맞는지도 검증 로직을 추가해야 할 것 같습니다
e.g. 2자 이상 10자 이하 입력

2024-11-04 00:12 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +        />
휴대폰 번호와 계좌번호도 전화번호 형식에 맞는지, 숫자값이 입력되는지 검증이 필요할 것 같아요

2024-11-04 02:33 UTC, corinthionia requested changes

2024-11-04 02:33 UTC, corinthionia commented on src/components/input/index.tsx
> +  errorMessage?: string | null;
Input 컴포넌트 수정할 필요는 없습니다! null 값 말고 undefined 값을 전달해 주세요

2024-11-04 02:33 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +    }
`test`로 검증 전에 `setAccountNumber` 하면 안 되지 않나요?!

2024-11-04 06:05 UTC, corinthionia requested changes

2024-11-04 06:05 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +          errorMessage={isNicknameAvailable === false ? '이미 존재하는 닉네임입니다' : false}
```suggestion
          confirmMessage={isNicknameAvailable && '사용 가능한 닉네임입니다'}
          errorMessage={!isNicknameAvailable && '이미 존재하는 닉네임입니다'}
```

2024-11-04 13:15 UTC, corinthionia requested changes

2024-11-04 13:15 UTC, corinthionia commented on src/pages/mypage/pages/user-profile/index.tsx
> +            height="17px"
여기 24px로 바꿔 주세요!

2024-11-05 00:37 UTC, Sieonn approved these changes

2024-11-05 01:39 UTC, corinthionia requested changes

2024-11-05 01:39 UTC, corinthionia commented on src/api/users/index.ts
> +export const patchUsersme = async (body: PatchUsersMeBody) => {
`patchUsersMe`로 수정해 주세요

2024-11-05 06:55 UTC, merged