[PREAM-136] 로그인 토큰 관리
team-pream/pream-web pull request #140
Opened 2024-11-06 10:49 UTC by jejukyj

### PR 제목

[PREAM-136] 로그인 토큰 관리

### 🔗 연관된 이슈 번호

close #128 

### ✨ 어떤 기능을 개발했나요?
- AccessToken이 만료되거나 유효하지 않은 경우 RefreshToken을 통해 AccessToken을 재발급하는 기능을 구현했습니다.
- RefreshToken이 만료되거나 유효하지 않은 경우 alert창과 함께 로그인 페이지로 리다이렉트 되도록 했습니다.

### ✅ 어떤 문제를 해결했나요?
- RefreshToken을 재발급 받을 때 Headers에 refreshToken이 아닌 accessToken이 붙는 오류 발생
  - 인터셉터 없이 직접 axios.post 사용하여 해결하였습니다.

### 🗂️ 관련 논의 내용 Link (Option)

### 🚀 결과 이미지 (Option)

[PREAM-136]: https://team-pream.atlassian.net/browse/PREAM-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-06 11:18 UTC, Sieonn approved these changes

2024-11-06 11:45 UTC, corinthionia requested changes

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +import { ERROR_CODE } from '@/constants/errorCode';
경로는 kebab-case로 작성해 주세요!

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +        const NewAccessToken = postResponse.data.accessToken;
첫 글자는 소문자로 변경해 주세요!

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +        return api(originalRequest);
👍🏻👍🏻

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +        console.log('postError:', e.response.data.errorCode);
console.log는 모두 삭제해도 될 거 같아요!

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +          window.location.href = '../login'; // 로그인 페이지로 redirect
`window.location.href = ROUTE_PATHS.LOGIN;`으로 변경해 주세요!

2024-11-06 11:45 UTC, corinthionia commented on src/api/api.ts
> +      window.location.href = './login';
여기도 `window.location.href = ROUTE_PATHS.LOGIN` !

2024-11-07 02:31 UTC, corinthionia commented on src/api/api.ts
> +          window.location.href = ROUTE_PATHS.LOGIN; // 로그인 페이지로 redirect
`localStorage.clear()` 도 하면 좋을 것 같아요!

2024-11-07 02:42 UTC, corinthionia approved these changes

2024-11-07 04:08 UTC, merged