[PREAM-51]구매하기 페이지 개발
team-pream/pream-web pull request #59
Opened 2024-10-29 10:48 UTC by Sieonn

### [PREAM-51]구매하기 페이지 개발

[PREAM-51]

### 🔗 연관된 이슈 번호

close #

### ✨ 어떤 기능을 개발했나요?
구매하기 페이지를 구현했습니다. 
- 결제 수단 중에 하나만 선택이 가능합니다.
- 카드결제 외에 다른 결제 수단을 선택하면 selector가 비활성화 됩니다.
### ✅ 어떤 문제를 해결했나요?

### 🗂️ 관련 논의 내용 Link (Option)

### 🚀 결과 이미지 (Option)

2024-10-29 11:04 UTC, jeonkyungwon commented on src/pages/purchase/components/order-total/index.tsx
> +const OrderTotal: React.FC = () => {
여기도 React.FC 명시하지 않도록 해주세요!

2024-10-29 14:25 UTC, corinthionia requested changes
이전 PR과 상당한 부분이 겹치기도 하고 develop 브랜치의 내용이 반영되지 않은 것 같아요!
내일 같이 rebase 다시 한번 해 봅시다!!

2024-10-29 14:25 UTC, corinthionia commented on src/App.tsx
> +import { Main, OnBoarding, Category, Login, Auth, Address, Detail } from '@/pages';
앗 여기에서는 경로가 잘 지정되어 있네요!

2024-10-29 14:25 UTC, corinthionia commented on src/api/detail/index.ts
> +
이전 PR에서 댓글 단 내용도 반영해 주시면 감사하겠습니다...!

2024-10-29 14:25 UTC, corinthionia commented on src/api/index.ts
> +
`develop` 브랜치의 내용을 반영해 주세요!

2024-10-29 14:25 UTC, corinthionia commented on src/pages/purchase/components/payments-methods/index.tsx
> +  ];
여기는 상수로 사용되기 때문에 컴포넌트 밖에서 정의해 주세요! 또한 상수는 `CARD_COMPANIES`와 같은 형식으로 작성해 주세요!

2024-10-31 10:14 UTC, corinthionia requested changes
이전 작업이랑 겹치는 내용이 많아 보여서 rebase 한번 해야 할 것 같아요!

2024-10-31 13:46 UTC, Sieonn commented on src/pages/purchase/components/payments-methods/index.tsx
> +  ];
이거 생성 위치는 어디에 해야할까요??? constants에 작성하면 되나요?

2024-10-31 14:25 UTC, corinthionia commented on src/pages/detail/index.styles.ts
>  export const Header = css`
변수명 소문자로 변경이 안 된 것 같아요!

2024-10-31 14:25 UTC, corinthionia commented on src/pages/purchase/components/address/index.styles.ts
> +export const addressBtn = css`
여기도 줄임말 말고 전체 이름으로 작성해 주세요! `addressButton`

2024-11-01 00:51 UTC, corinthionia approved these changes

2024-11-01 00:51 UTC, corinthionia commented on src/pages/purchase/index.tsx
> +  { id: 'woori', name: '우리' },
👍🏻👍🏻

2024-11-01 01:21 UTC, merged