[PREAM-15] 로그인 페이지 개발
team-pream/pream-web pull request #6
Opened 2024-10-24 07:53 UTC by jeonkyungwon

### PR 제목

[PREAM-15]  로그인 페이지 개발

### 🔗 연관된 이슈 번호

close #5 

### ✨ 어떤 기능을 개발했나요?
로그인 페이지 UI 구현
카카오 로그인 기능 구현
로그인 페이지 개발

### ✅ 어떤 문제를 해결했나요?
-

### 🗂️ 관련 논의 내용 Link (Option)
-

### 🚀 결과 이미지 (Option)
![image](https://github.com/user-attachments/assets/853cc008-0e8c-4980-a3d9-e27a04f30128)

2024-10-24 08:26 UTC, minju0423 commented on src/pages/auth/index.styles.ts
> +export const Wrapper = css`
style변수명 소문자로 시작해야할것같습니다.

2024-10-24 08:28 UTC, corinthionia requested changes

2024-10-24 08:28 UTC, corinthionia commented on public/icons/kakao-logo.svg
이미지 파일 이름에는 하이픈 말고 언더바 사용해 주세요! `kakao_logo.svg`

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/index.styles.ts
> +export const KakaoBtn = css`
줄임말 사용은 지양해 주세요! 길더라도 명확한 이름이 더 보기 좋고, 컨벤션으로도 존재하는 내용입니다!
`KakaoButton`

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/index.tsx
> +const Login: React.FC = () => {
`React.FC`는 명시하지 않는 게 좋습니다. [React React.FC 사용 지양하기](https://velog.io/@frombozztoang/React.FC-%EC%82%AC%EC%9A%A9-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0)
또한 컴포넌트 만들 때 화살표 함수 말고 `function` 키워드를 사용해 주세요! (컨벤션 문서에 적혀 있습니다!)

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/index.styles.ts
> +export const Wrapper = css`
변수 이름에 해당하기 때문에 첫 글자는 소문자로 작성해 주세요 🙂

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/index.tsx
> +      <button css={KakaoBtn} onClick={handleKakaoLogin}>
이벤트 핸들러의 이름은 `handle + 대상 + 이벤트명` 형식으로 작성해 주세요
e.g. `handleKakaoLoginButtonClick`

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/pages/kakao/index.tsx
> +      localStorage.setItem('needOnboarding', needOnboarding);
이 값은 별도로 저장하지 않아도 되지 않나요?

2024-10-24 08:28 UTC, corinthionia commented on src/pages/auth/pages/kakao/index.tsx
> +  return <div css={Wrapper}>로그인 중임다~</div>;
빈 화면이 렌더링되도록 변경해 주세요!

2024-10-24 08:28 UTC, corinthionia commented on src/pages/index.ts
> +export { default as OnBoarding } from './onboarding';
굿굿!

2024-10-24 08:42 UTC, jeonkyungwon commented on src/pages/auth/index.styles.ts
> +export const Wrapper = css`
넵 감사합니다!

2024-10-24 08:42 UTC, jeonkyungwon commented on public/icons/kakao-logo.svg
넵 감사합니다!
수정했습니다!

2024-10-24 08:42 UTC, jeonkyungwon commented on src/pages/auth/index.styles.ts
> +export const KakaoBtn = css`
명심하겠습니다!
감사합니다!

2024-10-24 08:45 UTC, jeonkyungwon commented on src/pages/auth/index.styles.ts
> +export const Wrapper = css`
넵 감사합니다~

2024-10-24 08:45 UTC, jeonkyungwon commented on src/pages/auth/index.tsx
> +      <button css={KakaoBtn} onClick={handleKakaoLogin}>
명심하겠습니다!
감사합니다!

2024-10-24 08:52 UTC, jeonkyungwon commented on src/pages/auth/pages/kakao/index.tsx
> +      localStorage.setItem('needOnboarding', needOnboarding);
![image](https://github.com/user-attachments/assets/33eef23f-2b63-4563-9e34-b2b96a1345e6)
로컬스토리지에 저장하고 있습니다!

2024-10-24 10:01 UTC, corinthionia commented on src/pages/auth/pages/kakao/index.tsx
> +      localStorage.setItem('needOnboarding', needOnboarding);
로컬스토리지에 저장할 필요가 없지 않나요?!

2024-10-24 23:59 UTC, corinthionia requested changes

2024-10-24 23:59 UTC, corinthionia commented on src/pages/auth/pages/kakao/index.tsx
> +        navigate('/');
그리고 로그인 완료 후 이전 로그인 화면으로 돌아갈 수 없게 replace를 사용해 주세요!
```suggestion
      if (needOnboarding === 'true') {
        navigate('/onboarding', ,  { replace: true });
      } else {
        navigate('/', ,  { replace: true });
```

2024-10-25 01:14 UTC, jeonkyungwon commented on src/pages/auth/index.tsx
> +const Login: React.FC = () => {
수정했습니다!
감사합니다~

2024-10-25 01:16 UTC, jeonkyungwon commented on src/pages/auth/pages/kakao/index.tsx
> +        navigate('/');
넵 수정했습니다~
감사합니다!

2024-10-25 01:37 UTC, corinthionia requested changes
`.env`에서 api 주소 변수명 변경 말고는 추가적인 수정 사항은 없을 것 같습니다!

2024-10-25 01:37 UTC, corinthionia commented on src/pages/auth/index.tsx
> +
`.env` 파일 내에 api 주소를 `BASE_URL`로 저장하고 있어서 다른 분들이 사용할 때 제대로 동작하지 않을 수 있을 것 같아요!
`.env` 파일 부분과 이 부분을 `VITE_BASE_URL`로 바꿔 주시면 감사하겠습니다 🙇‍♀️

2024-10-25 01:37 UTC, corinthionia commented on src/pages/auth/pages/kakao/index.tsx
> +        navigate('/', { replace: true });
👍🏻👍🏻

2024-10-25 01:43 UTC, jeonkyungwon commented on src/pages/auth/index.tsx
> +
수정했습니다!
감사합니다 ㅎㅎ

2024-10-25 01:46 UTC, corinthionia approved these changes
고생하셨습니다!!

2024-10-25 02:03 UTC, merged