[Pream-98] 회원 정보 등록 페이지 개발
team-pream/pream-web pull request #67
Opened 2024-10-30 05:22 UTC by jeonkyungwon

### PR 제목

[PREAM-98]

### 🔗 연관된 이슈 번호

close #66 

### ✨ 어떤 기능을 개발했나요?
사용자 정보 등록 기능 개발
닉네임 중복체크 기능 개발
반려동물 정보 등록 기능 개발
회원가입 페이지 UI 개발
### ✅ 어떤 문제를 해결했나요?
-
### 🗂️ 관련 논의 내용 Link (Option)
-
### 🚀 결과 이미지 (Option)
-

2024-10-30 05:33 UTC, Sieonn approved these changes
공통 컴포넌트 적용해서 리팩토링 진행해주세요.

2024-10-30 05:36 UTC, corinthionia requested changes
파일 변경이 너무 많은데 rebase 잘못되었나요?

2024-10-30 05:37 UTC, corinthionia commented
중간에 @jeonkyungwon
[Merge branch 'feature/PREAM-17' into feature/PREAM-98](https://github.com/team-pream/pream-web/pull/67/commits/8f0e3e5cd135e08af80d3a4e511553b9079d4a58) 이 커밋은 머지를 잘못하신 건가요?

2024-10-30 06:10 UTC, corinthionia requested changes

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +  const [nicknameAvailable, setNicknameAvailable] = useState<boolean | null>(null);
access token은 이미 로컬 스토리지에 저장했는데 state를 별도로 사용하시는 이유가 있나요?

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +  const mutation = usePatchOnboardingMutation(onNext);
조금 더 명확한 네이밍이 필요할 것 같습니다

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +        body: { nickname: formData.nickname } as CheckNicknameRequestBody,
타입이 맞지 않지 않나요?

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +      console.log('Nickname is available');
console.log는 지워 주세요

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +  });
hook을 또 다시 변수에 담는 이유가 있으신가요...?

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +    if (!accessToken || !formData.nickname) return;
access 토큰을 여기에서 이런 식으로 사용하는 것은 적절하지 않은 것 같습니다

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +  const mutation = usePatchOnboardingMutation(onNext);
비구조화 할당을 이용해 주세요
```suggestion
  const { mutation } = usePatchOnboardingMutation(onNext);
```

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +          <input
공통 컴포넌트로 적용해 주세요

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/firstStep/index.tsx
> +        ]}
`nextButton` 말고 추가적으로 스타일을 넘기는 이유가 있나요?

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +        <div css={progressBar(step === 4 ? 3 : step)} />
step을 숫자로만 표시하게 되면 어떤 단계인지 다른 개발자 분들이 이해하기 어렵습니다!
각 스텝에 대한 명확한 이름을 부여하는 게 더 좋을 것 같아요

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +            반가워요 <span css={highlightText}>임시언</span> 님!
여기도 사용자 정보 조회 api 사용해야겠네요

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/secondStep/index.tsx
> +        style={{ borderColor: formData.petType === 'dog' ? '#72dacd' : '' }}
인라인 스타일 사용은 지양해 주세요

2024-10-30 06:10 UTC, corinthionia commented on src/pages/onboarding/thirdStep/index.tsx
> +          onChange={(e) => setFormData({ ...formData, petName: e.target.value })}
타입을 지정해 주세요

2024-10-30 06:17 UTC, jeonkyungwon commented on src/api/user/checkNickname/index.ts
> +import { CheckNicknameRequestBody } from '@/types';
감사합니다! 수정 완료했습니다!

2024-10-30 06:51 UTC, jeonkyungwon commented on src/pages/onboarding/firstStep/index.styles.ts
> +export const nextButton = (isValid) => css`
넵 적용했습니다!

2024-10-30 06:58 UTC, jeonkyungwon commented on src/pages/onboarding/firstStep/index.tsx
> +export default function FirstStep({ onNext, setFormData, formData }: FirstStepProps) {
수정했습니다!

2024-10-30 08:07 UTC, jeonkyungwon commented on src/pages/onboarding/completeStep/index.tsx
> +    <div css={[textBox, { marginTop: '200px' }]}>
피그마 보시면 온보딩 3번째 단계에 
강아지 이름을 알려주세요 라는 문구가 다른 단계에 비해 아래에 위치해있어서 따로 넣어줬습니다.
따로 만들어서 수정하겠습니다!

2024-10-30 11:08 UTC, jeonkyungwon commented on src/pages/onboarding/firstStep/index.tsx
> +  const [nicknameAvailable, setNicknameAvailable] = useState<boolean | null>(null);
찾아본 바로는 state로 관리하는 것이 렌더링 흐름에 적합하다고 하여서 그렇습니다!
매번 로컬스토리지에 접근하면 컴포넌트가 재렌더링될 때마다 호출되어서 비효율적이라고 합니다. 
문제가 있다면 변경하겠습니다!

2024-10-30 11:12 UTC, jeonkyungwon commented on src/pages/onboarding/firstStep/index.tsx
> +        body: { nickname: formData.nickname } as CheckNicknameRequestBody,
수정했습니다!

2024-10-30 11:13 UTC, jeonkyungwon commented on src/pages/onboarding/firstStep/index.tsx
> +  });
변수에 담아두면서 요청 로직과 상태 관리를 코드에서 간결하고 일관되게 사용할 수 있어서 입니다.

2024-10-31 01:09 UTC, corinthionia requested changes

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +};
👍🏻👍🏻

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +};
이런 상수 값들은 컴포넌트 코드 밖 (inport문 아래)으로 변경해 주세요

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +  const renderStep = () => {
깔끔하네요 👍🏻

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +    <div css={wrapper}>
이 부분도 Layout 컴포넌트로 변경해 주세요

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/petType/index.tsx
> +  const isStep2Valid = formData.petType !== '';
step1, step2, step3로 되어 있는 부분들 전부 변경된 step 이름으로 바뀌면 좋을 것 같습니다!

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/petType/index.tsx
> +          onClick={() => setFormData({ ...formData, petType: 'dog' })}
mutate할 때 `toUpperCase()`를 사용해서 대문자로 변경 후 전송하고 있는데, 처음부터 대문자로 작성해도 되지 않을까요?
그리고 반려동물 타입이 정해져 있다 보니 상수로 관리하는 게 더 좋을 것 같습니다.

```javascript
const PET_TYPE = {
   DOG: 'DOG',
   CAT: 'CAT'
}

2024-10-31 01:09 UTC, corinthionia commented on src/pages/onboarding/petType/index.tsx
> +          style={{ borderColor: formData.petType === 'cat' ? '#72dacd' : '' }}
인라인 스타일이랑 css props로 넘기는 값이랑 무슨 차이인가요?
인라인 스타일은 지양해 주세요!

2024-10-31 01:09 UTC, corinthionia commented on src/queries/user/petProfile/index.ts
> +      const { body, accessToken } = data;
여기에서도 accessToken은 빼 주세요
axios interceptors에서 header를 미리 정의하여 필요없기 때문입니다

2024-10-31 01:09 UTC, corinthionia commented on src/queries/query-keys.ts
> +  GET_USERNAME: () => ['GET_USERNAME'],
동적인 값을 전달할 때에만 `() => {}` 형식으로 작성합니다! 여기에서는 넘겨주는 인자가 없으니 아래처럼 변경해 주세요
```suggestion
  GET_USERNAME: ['GET_USERNAME'],
```

2024-10-31 01:09 UTC, corinthionia commented on src/queries/user/userName/index.ts
> +    queryKey: QUERY_KEYS.GET_USERNAME(),
```suggestion
    queryKey: QUERY_KEYS.GET_USERNAME,
```

2024-10-31 02:16 UTC, jeonkyungwon commented on src/pages/onboarding/completeStep/index.tsx
> +        두부집사 님<br />
넵~~~!

2024-10-31 08:11 UTC, corinthionia requested changes

2024-10-31 08:11 UTC, corinthionia commented on src/api/user/check-nickname/index.ts
> +
`src/api/user` 밑에 폴더 여러 개를 작성하는 게 아니라, `src/api/user/index.ts`에 연관된 api를 모두 작성해 주셔야 합니다.

2024-10-31 08:11 UTC, corinthionia commented on src/api/user/pet-profile/index.ts
> +
이것도 `src/api/user/index.ts`

2024-10-31 08:11 UTC, corinthionia commented on src/api/user/user-profile/index.ts
> +
여기까지 다 `src/api/user/index.ts`에 들어가야 합니다

2024-10-31 08:11 UTC, corinthionia commented on src/pages/onboarding/completion/index.tsx
> +        {nickName} 님<br />
react query를 사용하는 이유는 서버에서 받은 데이터를 state에 저장하지 않기 위함입니다.
`data`로 response data`를 바로 받을 수 있기 때문에 아래처럼 변경해 주세요
```suggestion
  const handleCompleteButtonClick = () => {
    navigate('/', { replace: true });
  };

  return (
    <div css={textBox}>
      <Complete width="70px" />
      <Text typo="title1" color={theme.colors.green200}>
        {data.nickName} 님<br />
```

2024-10-31 08:11 UTC, corinthionia commented on src/pages/onboarding/index.tsx
> +        accessToken: localStorage.getItem('access') || '',
access token을 넘겨 주는 부분은 axios interceptor를 사용하는 부분 빼고 **모두** 지워 주세요

2024-10-31 08:11 UTC, corinthionia commented on src/pages/onboarding/pet-type/index.tsx
> +  }, []);
여기도 `data`를 `state`에 저장하지 말아 주세요

2024-10-31 08:11 UTC, corinthionia commented on src/pages/onboarding/user-info/index.tsx
> +  }, [data]);
여기도 지워 주세요

2024-10-31 08:11 UTC, corinthionia commented on src/types/index.ts
> +
`types/index.ts`가 아닌 `types/user/index.ts`로 이동해야 합니다.

2024-10-31 11:30 UTC, corinthionia approved these changes

2024-10-31 11:30 UTC, corinthionia commented on src/api/user/index.ts
> +import { PatchUserOnboardingBody } from '@/types/user';
이거 한 줄로 작성해 주세요!

2024-10-31 11:30 UTC, corinthionia commented on src/pages/onboarding/completion/index.tsx
> +        {data.nickname} 님<br />
👍🏻

2024-10-31 11:34 UTC, merged