feat: 메인페이지 카테고리 UI 구현 및 라우터 연결
team-pream/pream-web pull request #8
Opened 2024-10-24 11:34 UTC by jejukyj

### PR 제목

[PREAM-]

### 🔗 연관된 이슈 번호

close #7 

### ✨ 어떤 기능을 개발했나요?
- 카테고리 UI 구현
- 라우트 기능 구현

### ✅ 어떤 문제를 해결했나요?

### 🗂️ 관련 논의 내용 Link (Option)

### 🚀 결과 이미지 (Option)

2024-10-24 11:43 UTC, corinthionia requested changes

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.styles.ts
> +  /* background-color: beige; */
주석은 지워 주세요!

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.styles.ts
> +`;
`categoryIcon` 같은 이름이 어떨까요?

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.styles.ts
> +  }
그냥 `cursor: pointer;` 해도 적용됩니다!

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.tsx
> +  }, []);
react-query 사용해 주세요!!

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.tsx
> +  const nav = useNavigate();
주로 이렇게 씁니다 ㅎㅎ
```suggestion
  const navigate = useNavigate();
```

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.tsx
> +                      onClick={() => handleCategoryButtonClick(item.id)}
`handleCategoryButtonClick` 함수가 짧아서 별도로 분리 안 하고 이렇게 여기서 바로 써도 될 것 같아요!
```suggestion
                      onClick={() => navigate(item.id)}
```

2024-10-24 11:43 UTC, corinthionia commented on src/pages/main/index.tsx
> +              <p>'Loading..'</p>
이 부분은 일단은 제거해도 될 것 같아요!
나중에 시간 남으면 스켈레톤 컴포넌트 구현해 봅시당

2024-10-24 11:43 UTC, corinthionia commented
PR 이름도 형식에 맞게 바꿔 주세요!

2024-10-24 11:45 UTC, jejukyj commented on src/pages/main/index.styles.ts
> +  /* background-color: beige; */
넵!

2024-10-24 11:45 UTC, jejukyj commented on src/pages/main/index.styles.ts
> +`;
오 너무 좋습니당 바로 수정하겠습니다!

2024-10-24 11:46 UTC, jejukyj commented on src/pages/main/index.styles.ts
> +  }
헉.. 이제까지 저렇게 했는데..! 감사합니다!

2024-10-24 11:49 UTC, jejukyj commented on src/pages/main/index.tsx
> +  }, []);
아! 넵 수정하겠습니다!

2024-10-24 11:51 UTC, jejukyj commented on src/pages/main/index.tsx
> +                      onClick={() => handleCategoryButtonClick(item.id)}
오 바로 수정하겠습니다

2024-10-24 13:08 UTC, corinthionia requested changes

2024-10-24 13:08 UTC, corinthionia commented on src/pages/main/index.tsx
> +import { categoryIcon } from './index.styles';
여기 부분 한 줄로 줄여 주세요!
```suggestion
import { categoryList, categoryItems , categoryItem , categoryIcon} from './index.styles';
```

2024-10-24 13:08 UTC, corinthionia commented on src/pages/main/index.tsx
> +  refetch();
`refetch()` 하는 이유가 있으신가요?

2024-10-24 13:08 UTC, corinthionia commented on src/pages/main/index.tsx
> +              ?.filter((item: CategoryData) => item.id !== 4 && item.id !== 5)
여기는 카테고리 아이디 4번과 5번이 무엇을 의미하는지 모르니 상수화하면 좋을 것 같아요! 
```javascript
const CAT_WHEEL = 4;
const WALKING = 5;
```

아니면 '제외되는' 카테고리의 의미를 더 강조해서 아래처럼 추가적으로 작성해도 될 것 같아요!
```javascript 
const excludedCategories = [CAT_WHEEL, WALKING];

...

data?.filter((item: CategoryData) => !excludedCategories.includes(item.id))
```

2024-10-25 02:24 UTC, corinthionia approved these changes

2024-10-25 02:26 UTC, merged