[PREAM-124] 반려동물 프로필 편집 화면 개발
team-pream/pream-web pull request #81
Opened 2024-10-31 05:12 UTC by minju0423

### PR 제목

[PREAM-124] 반려동물 프로필 편집 화면 개발

### 🔗 연관된 이슈 번호

close #80 

### ✨ 어떤 기능을 개발했나요?
- 반려동물 프로필 편집 UI를 개발했습니다.

### ✅ 어떤 문제를 해결했나요?
- 반려동물 프로필을 편집할 수 있는 화면을 볼 수 있습니다.

### 🗂️ 관련 논의 내용 Link (Option)

### 🚀 결과 이미지 (Option)
<img width="500" alt="image" src="https://github.com/user-attachments/assets/cd353dda-2ddd-463c-af98-09d6a42a7795">

2024-10-31 05:24 UTC, corinthionia approved these changes

2024-10-31 05:24 UTC, corinthionia commented on src/App.tsx
> +          <Route path="/mypage/*" element={<Mypage />} />
👍🏻👍🏻👍🏻

2024-10-31 05:24 UTC, corinthionia commented on src/pages/mypage/pages/myinfo/index.tsx
> +    navigate(ROUTE_PATHS.LOGIN);
로그아웃 후 메인 페이지로 이동하는 게 더 좋을 것 같아요!

2024-10-31 06:04 UTC, minju0423 commented on src/pages/mypage/pages/myinfo/index.tsx
> +    navigate(ROUTE_PATHS.LOGIN);
useNavigate는 사용자의 정보를 남긴다고 해서` location.replace(ROUTE_PATHS.MAIN);` 로 변경하였습니다.

2024-10-31 06:42 UTC, jejukyj requested changes
카메라 아이콘은 다시 변경해주신다고 하니 그때 수정해주시면 될 것 같습니다
강아지와 고양이 선택하는 버튼 색상도 변경되었는데 나중에 디자인 컴포넌트 수정&추가 할 때 이것도 추가해주신다고 합니다. 이 부분도 나중에 수정해주시면 될 것 같아요!

2024-10-31 06:42 UTC, jejukyj commented on src/pages/mypage/pages/user-edit/index.styles.ts
> +  gap: 30px;
간격이 30px로 통일되어 있는데 약간씩 다 달라서 수정해주시면 좋을 것 같습니다🥲

2024-10-31 06:42 UTC, jejukyj commented on src/pages/mypage/pages/user-edit/index.styles.ts
> +`;
피그마에서 작업한 화면과 화면에서 보이는 전체 길이가 달라서 좀 짤려보이는 이슈를 이제야 확인했네요..💦 
버튼을 fixed로 고정을 하고 z-index를 설정하여 띄우는 방향으로 가는게 좋을 것 같습니다..

2024-10-31 06:42 UTC, jejukyj commented on src/pages/mypage/pages/user-edit/index.styles.ts
> +  box-shadow: 0 0 8px ${theme.colors.gray300};
변경사항이 좀 많죠,,,, 화면을 수정하면서 shadow 대신 border를 주는 것으로 수정하였습니다 참고해서 수정해주시면 감사하겠습니다🙇🏻‍♀️

2024-10-31 09:08 UTC, minju0423 commented on src/pages/mypage/pages/user-edit/index.styles.ts
> +  box-shadow: 0 0 8px ${theme.colors.gray300};
해당 사항 다 수정했습니다! 확인부탁드립니다아~

2024-11-01 01:22 UTC, jejukyj approved these changes
👍✨

2024-11-01 01:23 UTC, merged